[package]
name = "shiguredo_rtsp"
version = "2026.1.0-canary.0"
edition = "2024"
rust-version = "1.88"
description = "Sans I/O RTSP/1.0 Library"
readme = "README.md"
homepage = "https://github.com/shiguredo/rtsp-rs"
repository = "https://github.com/shiguredo/rtsp-rs"
license = "Apache-2.0"
include = ["/LICENSE", "/README.md", "/src/**"]

[workspace]
members = ["examples/rtsp_client", "pbt"]
exclude = ["fuzz"]

[dependencies]
md-5 = "0.11"
shiguredo_http11 = { version = "2026.6" }
